version: "2"

linters:
  default: none
  enable:
    - errcheck
    - staticcheck
    - unused
    - ineffassign

issues:
  exclude-rules:
    - linters:
        - staticcheck
      text: "SA1019|SA1029"
